kafka:
  brokers:
    - redpanda-0:9092
    - redpanda-1:9092
    - redpanda-2:9092

schemaRegistry:
  enabled: true
  urls:
    - http://redpanda-0:8081

redpanda:
  adminApi:
    enabled: true
    urls:
      - http://redpanda-0:9644
      - http://redpanda-1:9644
      - http://redpanda-2:9644